mentor
torontojs/torontojs.com pull request #113
Opened 2023-03-12 22:13 UTC by SamLamElectrician

**Added**
-Added a link for mentorship on Splash
-Added a route for mentorship
-Add mentorData in Data folder for fake data for now
-Create a mentorship page containing mentorship cards

**Needs**
-Link to google form on button
-real mentorData
-mentor link on splash needs an icon

2023-03-15 23:08 UTC, cixtor requested changes

2023-03-15 23:08 UTC, cixtor commented on src/App.js
> -import theme from "./theme"
Out of curiosity, why do you need to replace all double quotes with single quotes?

As an outsider, this looks like noise in what otherwise would be an easy-to-review merge request.

2023-03-15 23:08 UTC, cixtor commented on src/data/mentorData.js
> +  },
Is your expectation that mentors will hardcode a specific `“month”` to access their corresponding Calendly page?

Since this list is in a JavaScript file, I suppose that parameter could be turned into a dynamic value and that way allow mentors to only worry about adding their Calently username and the other portions of the URL are added programmatically.

2023-03-15 23:08 UTC, cixtor commented on src/components/MentorCard.js
> +}
The entire merge request appears to add visual components and no functionality, so I suggest to add screenshots to the pull-request description to make it easy for the reviewers to determine if visual changes are required before merging. Otherwise, they will have to guess what the HTML+CSS look like by looking at the code.

2023-03-16 04:17 UTC, SamLamElectrician commented on src/App.js
> -import theme from "./theme"
It was a setting I forgot to change on my prettier extension! Will fix it

2023-03-16 04:18 UTC, SamLamElectrician commented on src/data/mentorData.js
> +  },
Change this as well but it was a mistake when I was copying my link as a placeholder. The organizers still need to figure out a google form for a mentor feature!

2023-03-16 04:43 UTC, SamLamElectrician commented on src/components/MentorCard.js
> +}
Added some for clarity!

2024-01-10 20:37 UTC, closed without merging

2024-01-10 20:37 UTC, kieran commented
closing this PR as stale