Final Changes after PR Review!!
torontojs/torontojs.com pull request #149
Opened 2023-12-21 02:41 UTC by dreymoreau

Hello!! @usrrname @evert we have made the suggested changes from the previous draft pr! We are super excited to have worked on this!!! WOOO!!! :D

2023-12-24 22:14 UTC, kieran requested changes
Great work on this!

One final Q / suggestion: all the pictures are in `avatars/thumbs/` but there are no full-size images. Maybe we can drop the `thumbs` directory?

Also I noticed one of the images (elizabeth) still needs to be resized to match the others


Let me know if you want help parcel-izing the images - happy to chat!


Also, again: **super** impressed with this PR.

2023-12-24 22:14 UTC, kieran commented on package.json
> +  ],
I don't think we'll need these

2023-12-24 22:14 UTC, kieran commented on package.json
> +    "serve-static": "^1.15.0"
same here

2023-12-24 22:14 UTC, kieran commented on pages/volunteersNew.md
> +```js data-import="./volunteer_data.coffee"
seems like we're doing a lot of work to keep this page markdown - maybe we can just convert it to a react page like we do in the `/screens` folder? That way we don't need to do any weird build steps.

It was very clever, but I think maybe the simpler solution might be better for the long term

2023-12-24 22:14 UTC, kieran commented on pages/volunteersNew.md
> +```js data-import="./volunteer_data.coffee"
oh, it looks like maybe we did that already - can we delete this then?

2023-12-24 22:14 UTC, kieran commented on screens/volunteers/styles.sass
> +    margin-bottom: 5rem
one of the _very few_ linting things I tend to enforce is newlines at EOF

![image](https://github.com/torontojs/torontojs.com/assets/3444/370b7618-b1fe-48e8-8311-46bac8c17fb0)

Otherwise you end up with future commits where someone's editor will add the newline and you get a muddy git history full of files with no real changes

Instructions for making this automatic in VS Code here: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

2023-12-24 22:14 UTC, kieran commented on screens/volunteers/volunteers.json
> +]
same EOF newline comment here

2023-12-27 00:26 UTC, dreymoreau commented on .parcelrc
> -  "resolvers": ["@parcel/resolver-glob", "..."],
hey, we aren't clear on what you mean by back to the previous state, looked at the git history and couldnt find what it was prior

2023-12-27 00:33 UTC, dreymoreau commented on .proxyrc.js
> +const serveStatic = require('serve-static')
hey, this was the main problem we ran into with trying to find out to get images rendered and this was what we came up with after a bunch of trial and error, do u have any suggestions of how to configure parcel for image's with coffeescript?

2023-12-27 00:39 UTC, dreymoreau commented on components/profile_card/index.coffee
> +      src={if volunteer.avatarName then "/avatars/thumbs/#{volunteer.avatarName}.jpg" else DEFAULT_PROFILE_IMAGE}
thank you for sharing all of this info!! we came across importing the images one by one but thought this was a very not dynamic way of having the images rendered, it will for sure work for a few images but when its 30+ it feels like there should be a better way to do this, plus will make changes in the future easier for folks who want to also work on the website! is there a dynamic way of rendering images using parcel? or its only import one by one

2023-12-27 00:57 UTC, dreymoreau commented
@kieran hey! we made most changes that were suggested other then the image rendering with parcel! we tried to research ways on how to use parcel's image includes but came up with no answers on how to have the images rendered dynamically, it would be great to hop on a call to chat more about this, thank you!! :) also thanks for all your feedback on the pr! appreciate it!

2023-12-27 19:23 UTC, madcampos commented on screens/volunteers/volunteers.json
> +                "profileURLText": "gingerkiwi.blog",
```suggestion
                "name": "Elizabeth (Liz) McCready",
                "profileURL": "https://gingerkiwi.dev/",
                "profileURLText": "gingerkiwi.dev",
```

Suggesting changes based on issue https://github.com/torontojs/torontojs.com/issues/150

2023-12-27 23:58 UTC, kieran commented on .parcelrc
> -  "resolvers": ["@parcel/resolver-glob", "..."],
[included in PR](https://github.com/dreymoreau/torontojs.com/pull/2/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)

2023-12-27 23:59 UTC, kieran commented on .proxyrc.js
> +const serveStatic = require('serve-static')
covered this [in the PR](https://github.com/dreymoreau/torontojs.com/pull/2/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) as well

2023-12-28 00:01 UTC, kieran commented on components/profile_card/index.coffee
> +      src={if volunteer.avatarName then "/avatars/thumbs/#{volunteer.avatarName}.jpg" else DEFAULT_PROFILE_IMAGE}
TLDR: glob imports (I demo in the video in the [PR](https://github.com/dreymoreau/torontojs.com/pull/2))

2023-12-28 04:32 UTC, kieran reviewed
some very small notes but then it's 💯 

thanks!

2023-12-28 04:40 UTC, dreymoreau commented on screens/volunteers/index.coffee
> +        <Navbar />
changed the div//navbar to be 2 spaces and the whole screen went blank, tried just the div and still blank screen

2023-12-28 05:17 UTC, kieran commented on screens/volunteers/index.coffee
> +        <Navbar />
You need to indent the whole block

https://github.com/torontojs/torontojs.com/assets/3444/c4dad992-ca65-414a-bcdf-28bb91aa8e48

Indents are how some languages (like coffee and python) express "blocks"

Other languages (like Javascript and C) use braces: 
```
{ 
  block in here
}
```

2023-12-28 06:07 UTC, dreymoreau commented on screens/volunteers/index.coffee
> +        <Navbar />
oh cool!! good to know :D just updated and pushed :)

2023-12-28 20:07 UTC, kieran commented
Looks perfect! Just need to resolve this merge conflict before it can merge:
![image](https://github.com/torontojs/torontojs.com/assets/3444/06384422-dbfb-41cc-9c2d-482cb17edb8e)

I'm not 100% sure, but I think you need to do this locally with your fork somehow... maybe via the Sync Fork button, then the command line?
![image](https://github.com/torontojs/torontojs.com/assets/3444/8867e1ab-a872-4a85-8353-7ef3a26aaa5b)

TBH this might be a bit of a rabbit hole - I've never resolved a cross-repo merge conflict that GH couldn't handle.

Alternatively, you can open a new PR against `main` and copy the changed files again manually (and deleting the volunteers markdown file) - a bit of a pita, but it's straightforward and will work :-/

2024-01-03 01:25 UTC, closed without merging